# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class CompiledContract:
    r"""
    A compiled SilverScript contract: the locking script plus the metadata
    needed to build unlocking (signature) scripts for its entrypoints.
    """
    @property
    def contract_name(self) -> builtins.str:
        r"""
        The contract name from the SilverScript source.
        """
    @property
    def compiler_version(self) -> builtins.str:
        r"""
        The compiler version that produced this contract.
        """
    @property
    def without_selector(self) -> builtins.bool:
        r"""
        Whether the contract has a single entrypoint (no function selector).
        """
    @property
    def script(self) -> bytes:
        r"""
        The compiled locking script (redeem script) bytes.
        """
    @property
    def abi(self) -> builtins.list[FunctionAbiEntry]:
        r"""
        The contract ABI: one entry per callable entrypoint.
        """
    @property
    def state_layout(self) -> tuple[builtins.int, builtins.int]:
        r"""
        `(start, len)`: byte offset and length of the contract state within the script.
        """
    @property
    def template_hash(self) -> bytes:
        r"""
        The canonical length-bound template hash: a 32-byte digest over the
        script's template parts (the prefix before and suffix after the state
        region). Matches the SilverScript `templateHash(prefix, suffix)` builtin,
        so contracts can commit to this value and later reconstruct it on-chain.
        """
    def build_sig_script(self, function_name: builtins.str, args: typing.Optional[typing.Any] = None) -> bytes:
        r"""
        Build the signature (unlocking) script for an entrypoint.
        
        Args:
            function_name: The entrypoint to call.
            args: Native Python values (int, bool, str, bytes, list/tuple, or
                dict) matching the entrypoint's ABI input types. Omit or pass
                None for an entrypoint that takes no arguments.
        
        Returns:
            bytes: The signature (unlocking) script.
        
        Raises:
            SilverScriptError: If the entrypoint is unknown or an argument is
                invalid (wrong type, out of range, or too deeply nested).
        """
    def build_sig_script_for_covenant_decl(self, function_name: builtins.str, args: typing.Optional[typing.Any] = None, *, is_leader: builtins.bool = False) -> bytes:
        r"""
        Build the signature (unlocking) script for a covenant declaration entrypoint.
        
        Args:
            function_name: The covenant entrypoint to call.
            args: Native Python values matching the entrypoint's ABI input
                types. Omit or pass None for an entrypoint that takes no
                arguments.
            is_leader: Select the leader path for covenants that distinguish a
                leader from delegates (default: False).
        
        Returns:
            bytes: The signature (unlocking) script.
        
        Raises:
            SilverScriptError: If the entrypoint is unknown or an argument is
                invalid (wrong type, out of range, or too deeply nested).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class DebugCallResult:
    r"""
    The outcome of a `debug_call` simulation.
    """
    @property
    def success(self) -> builtins.bool:
        r"""
        True if the simulated spend passed script validation.
        """
    @property
    def error(self) -> typing.Optional[builtins.str]:
        r"""
        The script engine error message on failure; None on success.
        """
    @property
    def failure(self) -> typing.Optional[FailureReport]:
        r"""
        The source-level failure report (failing statement, call stack, and
        per-frame variables); None on success or when execution failed before
        the debug session started (e.g. in the signature script).
        """
    @property
    def console(self) -> builtins.list[builtins.str]:
        r"""
        Output captured from the contract's `console.log` calls, in execution
        order.
        """
    @property
    def function_name(self) -> builtins.str:
        r"""
        The entrypoint that was called (resolved to the first ABI entry when
        `function_name` was omitted).
        """
    @property
    def trace(self) -> typing.Optional[builtins.list[TraceStep]]:
        r"""
        The per-statement execution trace, in execution order; None unless
        `debug_call` was invoked with `trace=True`. On failure the trace covers
        the statements up to and including the failing one: the last entry is
        the failing statement, snapshotted when it was reached.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class DebugVariable:
    r"""
    A variable decoded from the script engine's stacks at a failure site,
    presented in source-level terms.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        The variable name from the SilverScript source.
        """
    @property
    def type_name(self) -> builtins.str:
        r"""
        The SilverScript type name (e.g. `int`, `byte[4]`, `State`).
        """
    @property
    def origin(self) -> builtins.str:
        r"""
        Where the variable comes from: `local`, `arg`, `state` (contract
        field), `ctor` (constructor argument), or `const`.
        """
    @property
    def display(self) -> builtins.str:
        r"""
        The value formatted for display, following the type (e.g. bytes are
        hex-encoded, `State` values render as objects).
        """
    @property
    def value(self) -> typing.Any:
        r"""
        The decoded value as a native Python object (`int`, `bool`, `bytes`,
        `str`, `list`, or `dict`). None if the value could not be decoded.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FailureFrame:
    r"""
    One frame of a failure report: a function on the (inlined) call stack at
    the point the script failed, with the variables in scope there.
    """
    @property
    def function_name(self) -> builtins.str:
        r"""
        The function executing in this frame.
        """
    @property
    def line(self) -> typing.Optional[builtins.int]:
        r"""
        1-based source line: the failure site for the innermost frame, the
        call site for caller frames. None when no source mapping exists.
        """
    @property
    def variables(self) -> builtins.list[DebugVariable]:
        r"""
        The variables in scope in this frame (locals, arguments, contract
        state, and constructor arguments; constants are omitted).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FailureReport:
    r"""
    A source-level report of why a debugged contract call failed: the failing
    statement, the inlined call stack, and the variables in scope per frame.
    
    `str()` (or `render()`) formats the report the way the SilverScript CLI
    debugger prints it, including source context lines.
    """
    @property
    def message(self) -> builtins.str:
        r"""
        Human-readable failure description (the script engine error).
        """
    @property
    def frames(self) -> builtins.list[FailureFrame]:
        r"""
        The call stack at the failure, innermost frame first.
        """
    def render(self) -> builtins.str:
        r"""
        Format the report for terminal display: failing source lines with
        context, plus each frame's variables.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class FunctionAbiEntry:
    r"""
    A single callable entrypoint in a compiled contract's ABI.
    """
    @property
    def name(self) -> builtins.str: ...
    @property
    def inputs(self) -> builtins.list[FunctionInputAbi]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class FunctionInputAbi:
    r"""
    A single input parameter of a contract entrypoint.
    """
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SilverScriptError(builtins.Exception):
    r"""
    Raised when SilverScript compilation or signature-script construction fails.
    """
    ...

@typing.final
class TraceStep:
    r"""
    One pause of a traced execution: an executed source statement, with the
    variables that were in scope when it was reached. What the CLI debugger
    shows on each `step`, recorded instead of printed.
    """
    @property
    def line(self) -> typing.Optional[builtins.int]:
        r"""
        1-based source line of the statement. None when no source mapping
        exists (e.g. generated dispatch code).
        """
    @property
    def function_name(self) -> typing.Optional[builtins.str]:
        r"""
        The function the statement belongs to (after inlining); None outside
        any mapped function.
        """
    @property
    def statement(self) -> typing.Optional[builtins.str]:
        r"""
        The statement's source text (the active line, trimmed).
        """
    @property
    def variables(self) -> builtins.list[DebugVariable]:
        r"""
        The variables in scope when the statement was reached — before it
        executes, so a local it defines appears from the following step on.
        """
    def __repr__(self) -> builtins.str: ...

def compile(source: builtins.str, constructor_args: typing.Optional[typing.Any] = None, *, allow_entrypoint_return: builtins.bool = False, record_debug_infos: builtins.bool = False) -> CompiledContract:
    r"""
    Compile SilverScript `source` into a `CompiledContract`.
    
    **Experimental:** SilverScript and these bindings are under active
    development; the API and the compiler's output may change in breaking ways
    between releases. See the `kaspa.experimental.silverscript` module docs.
    
    Args:
        source: The SilverScript contract source.
        constructor_args: Native Python values matching the contract's
            constructor parameters. Omit or pass None for a contract with no
            constructor parameters.
        allow_entrypoint_return: Permit entrypoints that return a value
            (default: False).
        record_debug_infos: Record debug information during compilation
            (default: False).
    
    Returns:
        CompiledContract: The compiled contract.
    
    Raises:
        SilverScriptError: If compilation fails (syntax error, type error, or
            incompatible pragma).
    """

def debug_call(source: builtins.str, function_name: typing.Optional[builtins.str] = None, args: typing.Optional[typing.Any] = None, constructor_args: typing.Optional[typing.Any] = None, tx: typing.Optional[typing.Any] = None, trace: builtins.bool = False) -> DebugCallResult:
    r"""
    Debug a SilverScript contract call by simulating the full spend locally.
    
    **Experimental:** SilverScript and these bindings are under active
    development; the API may change in breaking ways between releases.
    
    Compiles `source` with debug info, builds a synthetic transaction that
    spends the contract's P2SH UTXO with a call to the chosen entrypoint, and
    executes it through SilverScript's source-level debug engine. The result
    reports pass/fail; on failure it includes a source-level report with the
    failing statement, the call stack, and the decoded variables (locals,
    arguments, contract state) in each frame. `console.log` output is captured
    either way.
    
    This simulates script validation on a synthetic transaction — it does not
    touch the network and says nothing about fees, mass, or maturity.
    
    Args:
        source: The SilverScript contract source.
        function_name: The entrypoint to call. Defaults to the contract's
            first entrypoint. For covenant functions, use the source-level
            name (e.g. `"add"`).
        args: Native Python values matching the entrypoint's parameters. For
            covenant transition functions the leading `State` parameter is
            synthesized from the scenario's output states — pass only the
            source-level arguments after it.
        constructor_args: Native Python values for the contract's constructor
            parameters.
        tx: Optional transaction scenario dict. Defaults to a single-input,
            single-output spend of the contract. Keys: `version` (default 1),
            `lock_time` (default 0), `active_input_index` (default 0; the
            input being debugged), `inputs`, and `outputs`. Each input dict
            accepts `utxo_value` (required), `covenant_id` (32 bytes or hex),
            `state` (dict of contract state fields carried by the spent UTXO),
            `constructor_args`, `prev_txid`, `prev_index`, `sequence`,
            `sig_op_count`, `signature_script`, and `utxo_script` (raw bytes
            overrides). Each output dict accepts `value` (required),
            `covenant_id`, `authorizing_input`, `state` (the post-transition
            contract state to verify), `constructor_args`, `script`, and
            `p2pk_pubkey`.
        trace: When True, record a per-statement execution trace on
            `result.trace`: each executed statement with its source line,
            enclosing function, and the variables in scope when it was
            reached. Tracing changes what is recorded, not what executes.
            Covenant transition calls record no per-statement pauses (the
            engine verifies their bodies as a whole, as in the CLI debugger);
            the failure report still decodes them on failure.
    
    Returns:
        DebugCallResult: The simulation outcome. Script failures are reported
            in the result, not raised.
    
    Raises:
        SilverScriptError: If compilation fails, the entrypoint or an argument
            is invalid, or the `tx` scenario is malformed.
    """

