# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class CompiledContract:
    r"""
    A compiled SilverScript contract: the locking script plus the metadata
    needed to build unlocking (signature) scripts for its entrypoints.
    """
    @property
    def contract_name(self) -> builtins.str:
        r"""
        The contract name from the SilverScript source.
        """
    @property
    def compiler_version(self) -> builtins.str:
        r"""
        The compiler version that produced this contract.
        """
    @property
    def without_selector(self) -> builtins.bool:
        r"""
        Whether the contract has a single entrypoint (no function selector).
        """
    @property
    def script(self) -> bytes:
        r"""
        The compiled locking script (redeem script) bytes.
        """
    @property
    def abi(self) -> builtins.list[FunctionAbiEntry]:
        r"""
        The contract ABI: one entry per callable entrypoint.
        """
    @property
    def state_layout(self) -> tuple[builtins.int, builtins.int]:
        r"""
        `(start, len)`: byte offset and length of the contract state within the script.
        """
    def build_sig_script(self, function_name: builtins.str, args: typing.Optional[typing.Any] = None) -> bytes:
        r"""
        Build the signature (unlocking) script for an entrypoint.
        
        Args:
            function_name: The entrypoint to call.
            args: Native Python values (int, bool, str, bytes, list/tuple, or
                dict) matching the entrypoint's ABI input types. Omit or pass
                None for an entrypoint that takes no arguments.
        
        Returns:
            bytes: The signature (unlocking) script.
        
        Raises:
            SilverScriptError: If the entrypoint is unknown or an argument is
                invalid (wrong type, out of range, or too deeply nested).
        """
    def build_sig_script_for_covenant_decl(self, function_name: builtins.str, args: typing.Optional[typing.Any] = None, *, is_leader: builtins.bool = False) -> bytes:
        r"""
        Build the signature (unlocking) script for a covenant declaration entrypoint.
        
        Args:
            function_name: The covenant entrypoint to call.
            args: Native Python values matching the entrypoint's ABI input
                types. Omit or pass None for an entrypoint that takes no
                arguments.
            is_leader: Select the leader path for covenants that distinguish a
                leader from delegates (default: False).
        
        Returns:
            bytes: The signature (unlocking) script.
        
        Raises:
            SilverScriptError: If the entrypoint is unknown or an argument is
                invalid (wrong type, out of range, or too deeply nested).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FunctionAbiEntry:
    r"""
    A single callable entrypoint in a compiled contract's ABI.
    """
    @property
    def name(self) -> builtins.str: ...
    @property
    def inputs(self) -> builtins.list[FunctionInputAbi]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class FunctionInputAbi:
    r"""
    A single input parameter of a contract entrypoint.
    """
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> builtins.str:
        r"""
        SilverScript type, e.g. `"int"`, `"byte[32]"`, `"pubkey"`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class SilverScriptError(builtins.Exception):
    r"""
    Raised when SilverScript compilation or signature-script construction fails.
    """
    ...

def compile(source: builtins.str, constructor_args: typing.Optional[typing.Any] = None, *, allow_entrypoint_return: builtins.bool = False, record_debug_infos: builtins.bool = False) -> CompiledContract:
    r"""
    Compile SilverScript `source` into a `CompiledContract`.
    
    **Experimental:** SilverScript and these bindings are under active
    development; the API and the compiler's output may change in breaking ways
    between releases. See the `kaspa.experimental.silverscript` module docs.
    
    Args:
        source: The SilverScript contract source.
        constructor_args: Native Python values matching the contract's
            constructor parameters. Omit or pass None for a contract with no
            constructor parameters.
        allow_entrypoint_return: Permit entrypoints that return a value
            (default: False).
        record_debug_infos: Record debug information during compilation
            (default: False).
    
    Returns:
        CompiledContract: The compiled contract.
    
    Raises:
        SilverScriptError: If compilation fails (syntax error, type error, or
            incompatible pragma).
    """

