use crate::{
    address::PyAddress,
    wallet::core::{
        account::kind::PyAccountKind, deterministic::PyAccountId, storage::keydata::PyPrvKeyDataId,
        utxo::balance::PyBalance,
    },
};
use kaspa_utils::hex::ToHex;
use kaspa_wallet_core::{
    account::descriptor::{AccountDescriptor, AccountDescriptorProperty, AccountDescriptorValue},
    storage::AssocPrvKeyDataIds,
};
use pyo3::prelude::*;
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

#[gen_stub_pyclass]
#[pyclass(name = "AccountDescriptor")]
#[derive(Clone)]
pub struct PyAccountDescriptor(AccountDescriptor);

#[gen_stub_pymethods]
#[pymethods]
impl PyAccountDescriptor {
    /// The account kind (e.g. Bip32, Keypair, MultiSig).
    #[getter]
    pub fn get_kind(&self) -> PyAccountKind {
        PyAccountKind::from(self.0.kind)
    }

    /// The account id.
    #[getter]
    pub fn get_account_id(&self) -> PyAccountId {
        PyAccountId::from(self.0.account_id)
    }

    /// The user-assigned account name, or None if unset.
    #[getter]
    pub fn get_account_name(&self) -> Option<String> {
        self.0.account_name.clone()
    }

    /// The current balance of the account, or None if not yet known.
    #[getter]
    pub fn get_balance(&self) -> Option<PyBalance> {
        self.0.balance.clone().map(PyBalance::from)
    }

    /// The associated prv key data ids
    #[getter]
    pub fn get_prv_key_data_ids(&self) -> Option<Vec<PyPrvKeyDataId>> {
        match &self.0.prv_key_data_ids {
            AssocPrvKeyDataIds::None => None,
            AssocPrvKeyDataIds::Single(prv_key_id) => Some(vec![PyPrvKeyDataId::from(prv_key_id)]),
            AssocPrvKeyDataIds::Multiple(prv_key_ids) => {
                Some(prv_key_ids.iter().map(PyPrvKeyDataId::from).collect())
            }
        }
    }

    /// The current receive address as a string, or None if not available.
    #[getter]
    pub fn get_receive_address(&self) -> Option<PyAddress> {
        self.0.receive_address.as_ref().map(PyAddress::from)
    }

    /// The current change address as a string, or None if not available.
    #[getter]
    pub fn get_change_address(&self) -> Option<PyAddress> {
        self.0.change_address.as_ref().map(PyAddress::from)
    }

    /// All addresses of the account
    pub fn get_addresses(&self) -> Option<Vec<PyAddress>> {
        self.0
            .addresses
            .as_ref()
            .map(|addrs| addrs.iter().map(PyAddress::from).collect())
    }

    /// The BIP44 account index. None for account kinds that are not derived from
    /// an account index (e.g. keypair accounts).
    #[getter]
    pub fn get_account_index(&self) -> Option<u64> {
        match self
            .0
            .properties
            .get(&AccountDescriptorProperty::AccountIndex)
        {
            Some(AccountDescriptorValue::U64(v)) => Some(*v),
            _ => None,
        }
    }

    /// Extended public keys associated with the account, formatted as strings.
    /// None for account kinds that don't expose xpubs (e.g. keypair accounts).
    #[getter]
    pub fn get_xpub_keys(&self) -> Option<Vec<String>> {
        match self.0.properties.get(&AccountDescriptorProperty::XpubKeys) {
            Some(AccountDescriptorValue::XPubKeys(keys)) => {
                Some(keys.iter().map(|k| k.to_string(None)).collect())
            }
            _ => None,
        }
    }

    /// Whether the account uses ECDSA signatures (vs Schnorr). None if not applicable.
    #[getter]
    pub fn get_ecdsa(&self) -> Option<bool> {
        match self.0.properties.get(&AccountDescriptorProperty::Ecdsa) {
            Some(AccountDescriptorValue::Bool(v)) => Some(*v),
            _ => None,
        }
    }

    /// Number of receive addresses derived so far for this account. The next
    /// receive address generated by `accounts_create_new_address` will be at this
    /// index. None for account kinds without HD derivation.
    #[getter]
    pub fn get_receive_address_index(&self) -> Option<u32> {
        match self
            .0
            .properties
            .get(&AccountDescriptorProperty::DerivationMeta)
        {
            Some(AccountDescriptorValue::AddressDerivationMeta(v)) => Some(v.receive()),
            _ => None,
        }
    }

    /// Number of change addresses derived so far for this account. The next
    /// change address generated by `accounts_create_new_address` will be at this
    /// index. None for account kinds without HD derivation.
    #[getter]
    pub fn get_change_address_index(&self) -> Option<u32> {
        match self
            .0
            .properties
            .get(&AccountDescriptorProperty::DerivationMeta)
        {
            Some(AccountDescriptorValue::AddressDerivationMeta(v)) => Some(v.change()),
            _ => None,
        }
    }

    /// The string representation.
    ///
    /// Returns:
    ///     str: The AccountDescriptor as a string.
    fn __repr__(&self) -> String {
        let name = match &self.0.account_name {
            Some(name) => format!("'{}'", name),
            None => "None".to_string(),
        };
        format!(
            "AccountDescriptor(kind={}, account_id='{}', account_name={})",
            self.0.kind,
            self.0.account_id.to_hex(),
            name
        )
    }
}

impl From<AccountDescriptor> for PyAccountDescriptor {
    fn from(value: AccountDescriptor) -> Self {
        Self(value)
    }
}
