# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class WalletCustomError(builtins.Exception):
    r"""
    Custom wallet error
    """
    ...

@typing.final
class WalletError(builtins.Exception):
    r"""
    General catch-all wallet error
    """
    ...

