# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class CompiledContract:
    r"""
    A compiled SilverScript contract: the locking script plus the metadata
    needed to build unlocking (signature) scripts for its entrypoints.
    """
    @property
    def contract_name(self) -> builtins.str:
        r"""
        The contract name from the SilverScript source.
        """
    @property
    def compiler_version(self) -> builtins.str:
        r"""
        The compiler version that produced this contract.
        """
    @property
    def without_selector(self) -> builtins.bool:
        r"""
        Whether the contract has a single entrypoint (no function selector).
        """
    @property
    def script(self) -> bytes:
        r"""
        The compiled locking script (redeem script) bytes.
        """
    @property
    def abi(self) -> builtins.list[FunctionAbiEntry]:
        r"""
        The contract ABI: one entry per callable entrypoint.
        """
    @property
    def state_layout(self) -> tuple[builtins.int, builtins.int]:
        r"""
        `(start, len)` byte offsets of the contract state within the script.
        """
    def build_sig_script(self, function_name: builtins.str, args: typing.Optional[typing.Any] = None) -> bytes:
        r"""
        Build the signature (unlocking) script for `function_name`.
        
        `args` are native Python values (int/bool/str/bytes/list/dict) matching
        the function's ABI input types.
        """
    def build_sig_script_for_covenant_decl(self, function_name: builtins.str, args: typing.Optional[typing.Any] = None, *, is_leader: builtins.bool = False) -> bytes:
        r"""
        Build the signature script for a covenant declaration entrypoint.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FunctionAbiEntry:
    r"""
    A single callable entrypoint in a compiled contract's ABI.
    """
    @property
    def name(self) -> builtins.str: ...
    @property
    def inputs(self) -> builtins.list[FunctionInputAbi]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class FunctionInputAbi:
    r"""
    A single input parameter of a contract entrypoint.
    """
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> builtins.str:
        r"""
        SilverScript type, e.g. `"int"`, `"byte[32]"`, `"pubkey"`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class SilverScriptError(builtins.Exception):
    r"""
    Raised when SilverScript compilation or signature-script construction fails.
    """
    ...

def compile(source: builtins.str, constructor_args: typing.Optional[typing.Any] = None, *, allow_entrypoint_return: builtins.bool = False, record_debug_infos: builtins.bool = False) -> CompiledContract:
    r"""
    Compile SilverScript `source` into a `CompiledContract`.
    
    `constructor_args` are native Python values matching the contract's
    constructor parameters.
    """

